### ISSUE TITLE
opendata page has lost content

### ISSUE THREAD

**Issue by rgrp** [okfn/foundation#207]
* Video is missing
* share this links missing
* missing large amounts of content (e.g. definition of key terms) (I was just looking for this to link it to someone and found it had disappeared :-) ...)

**Comment by daonb** [comment]
Seems like it's fixed.

**Comment by morchickit** [comment]
It is fixed!

**Comment by rgrp** [comment]
@morchickit how is this fixed? There is still no video and lots of the content is still missing ;-)

**Comment by morchickit** [comment]
then in this round WONTFIX. 
(also need  more updates than that since we speak about 2 years ago, so we will open a new issue when the time is right)

**Comment by rgrp** [comment]
@morchickit ok so this is a WONTFIX - not FIXED.

Also why do we need updates - all the issues mentioned are still outstanding ;-)

But understand if you are doing a spring clean - but note no-one is likely to flag this in future since no-one will remember what we had ...
